### ISSUE TITLE
Front end design

### ISSUE THREAD

**Issue by JerameyATyler** [JerameyATyler/ihelped.today#5]
Need basic design principles to follow for making sure something generally looks good. Bullets points are probably enough to push me in a direction, e.g. Always use colors that are evenly spaced on the color wheel... . Need:
 - colors
 - fonts
 - font sizes
 - basic dos/don't
 - links to recommended resources where I can learn quickly.

**Comment by marteo2** [comment]
http://www.color-hex.com/color-palette/45117 Bright version color palette, colors can be used in combination and as accent colors

http://www.color-hex.com/color-palette/45118 Muted version color palette. 

^ These are a general idea of colors based off of popular schemes in stock images with related content

http://webaim.org/resources/contrastchecker/ Use this website to check text contrast, enter in the foreground and background colors and make sure you are using large enough text and vibrant enough colors that it passes web accessibility standards.

https://howtogetonline.com/best-google-font-combinations-currently-trending.php 
This is a listicle outlining some good combinations of open access google fonts that can be imported straight into styling sheets, keep in mind sans serif fonts are advisable on screens as they are easier to read. Large decorative text can be in serif fonts, but be careful so that you don't deliver branding that seems old-fashioned or off-message.

Links to some good and recommended fonts that are highly legible -->
https://fonts.google.com/specimen/Open+Sans
https://fonts.google.com/specimen/Muli
https://fonts.google.com/specimen/Didact+Gothic

**Comment by JerameyATyler** [comment]
Awesome. This is exactly what I needed. Thanks Liv.
